### ISSUE TITLE
Certaines valeurs n'apparaissent pas sur la carte.

### ISSUE THREAD

**Issue by liszto** [etalab/covid19-dashboard#39]
Il arrive (probablement souvent mais il faudrait que je vérifie journée / journée) que les valeurs ne s'affichent pas alors que les fichiers pour cette journée sont bien renseignés.
Exemple pour la journée du 27/01 : 
![image](https://user-images.githubusercontent.com/408031/77223204-af453b00-6b5a-11ea-920f-3e724c4de390.png)

Sur la carte il semble y avoir 0 malgré les 3 entrées dans le graphique.
Dans les fichiers en date du 27, je peux voir ceci : 
```
date: 2020-02-27
source:
  nom: ARS Auvergne Rhône-Alpes
  url: https://www.auvergne-rhone-alpes.ars.sante.fr/system/files/2020-02/200227_ARSARA_CP_2_cas_Covid-19_74_0.pdf
donneesRegionales:
  nom: Auvergne Rhône-Alpes
  code: REG-84
  casConfirmes: 2
  deces: 0
donneesDepartementales:
  - nom: Haute-Savoie
    code: DEP-74
    casConfirmes: 2
    deces: 0
```
On devrait avoir des données visuelles au niveau du département de Haute-Savoie ou de la région AURA mais ce n'est pas le cas.

Le 3ème cas doit venir probablement du fichier de la région Nouvelle Aquitaine. Etant donné qu'il y a un cas recensé depuis le 24 janvier. 

Hors aucun n'apparait sur la carte. Je pourrais jeter un oeil au code de cette partie si besoin.
